version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: edm_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://admin:password@db:5432/edm_db
      JWT_SECRET: supersecret
    depends_on:
      - db

volumes:
  postgres_data:
